export const PRESS_NUMERIC_BUTTON = 'PRESS_NUMERIC_BUTTON'
export const PRESS_ROUND_BUTTON = 'PRESS_ROUND_BUTTON'
export const REMOVE_TYPED_DIGIT = 'REMOVE_TYPED_DIGIT'
export const ADD_GUESS = 'ADD_GUESS'
export const ADD_SCORE = 'ADD_SCORE'
export const TOGGLE_NUMERIC_BUTTONS_VISIBILITY =
  'TOGGLE_NUMERIC_BUTTONS_VISIBILITY'
