export const PRESS_NUMERIC_BUTTON = 'PRESS_NUMERIC_BUTTON'
export const PRESS_ROUND_BUTTON = 'PRESS_ROUND_BUTTON'
export const DISCARD_TYPED_DIGIT = 'DISCARD_TYPED_DIGIT'
export const TOGGLE_NUMERIC_BUTTONS_VISIBILITY =
  'TOGGLE_NUMERIC_BUTTONS_VISIBILITY'
export const GIVE_DIGITS_TO_BOT = 'GIVE_DIGITS_TO_BOT'
export const SAVE_DIGITS = 'SAVE_DIGITS'
export const FETCH_DIGITS = 'FETCH_DIGITS'
