export const TYPE_DIGIT = 'TYPE_DIGIT'
export const DISCARD_TYPED_DIGIT = 'DISCARD_TYPED_DIGIT'
export const FETCH_DIGITS_SUCCESS = 'FETCH_DIGITS_SUCCESS'
export const FETCH_DIGITS_FAILURE = 'FETCH_DIGITS_FAILURE'
